### ISSUE TITLE
SuperCrypta stuck

### ISSUE THREAD

**Issue by redefinio** [supercrypta/supercrypta.github.io#5]
Anywhere I click, it does nothing, the info doesn't update also. 

I tried deleting SuperCrypta and installing it again, restarting computer, restarting the Notification Center (with AcitvityMonitor) and it's still stuck :( Hope you will help me to fix this

**Comment by ricardo85x** [comment]
Hi Sorry for this problem.
The first thing you have to do is edit this comment and remove the image :) It has sensitive information.

Did you try to update? We did release a new version today (0.63)

Let me know if the new version fixes the problem.

**Comment by redefinio** [comment]
I really don't care that someone might know which coins I'm trading :D But ok, I deleted the screenshot. Yes, I did install the update. :/

**Comment by ricardo85x** [comment]
You can download this version.
Copy to Applications folder Than run it.
It will wipe all your data : /

test if it working. If so you can download again the last version from App store, because this version will wipe your data every time you run it 💣 

[Super Crypta.zip](https://github.com/supercrypta/supercrypta.github.io/files/1582537/Super.Crypta.zip)

**Comment by redefinio** [comment]
It did work, I mean it wiped my data, but it still doesn't work as it should :( Now I can't add coins. Search works, I select ETH, but it does not appear in the list and the list remains empty

**Comment by ricardo85x** [comment]
What mac os version are you using?

**Comment by redefinio** [comment]
Mac OS High Sierra
10.13.2

**Comment by ricardo85x** [comment]
Ok

Close SupeCrypta

Open Finder and type:

Command + SHIFT + G
type: ~/Library

Delete this:

Application Scripts/com.ricardoft.Cryptonator.SuperCrypta
Application Scripts/com.ricardoft.SuperCryptaHelper
Containers/com.ricardoft.Cryptonator.SuperCrypta
Containers/com.ricardoft.SuperCryptaHelper
Group Containers/B3YXS69JAV.group.com.ricardoft.supercrypta

Open SuperCrypta

It should be like fresh install

**Comment by redefinio** [comment]
I still can't add coins :(

**Comment by ricardo85x** [comment]
Could you try it with another user on your mac? Just to make sure.
Also, can you access https://coinmarketcap.com from your browser?

**Comment by redefinio** [comment]
It works with the Guest user. Coinmarketcap.com is accessible

**Comment by redefinio** [comment]
<img width="435" alt="screen shot 2017-12-22 at 17 03 19" src="https://user-images.githubusercontent.com/18326359/34302537-0a4378de-e73a-11e7-877e-8b5709a4701b.png">
I always get this when opening notification center

**Comment by ricardo85x** [comment]
Are you using the latest version of the store or the file I sent?
You can delete de version I sent and use the official.

This message will disappear if you click Always Allow, and use the version from the store.
Maybe guest users do not let you save preferences. So this popup appears every time.
Do you use some firewall with your default user?
Maybe it is blocking supercrypta

**Comment by redefinio** [comment]
I get this message on the main user, Guest user works perfect. I think I don't use any firewall, not that I know. Where could I check? BTW, it's probably not the case because it worked fine, I use SuperCrypta for 2 days and only today it stopped working. Then I saw that the update is available, updated it, but it still didn't work. After your suggestions, i wiped all my data, now it's not stuck, but I can't add any coins. It just shows empty list (even default ETH and BTC coins are not shown).

**Comment by ricardo85x** [comment]
I will try https://itunes.apple.com/br/app/app-cleaner-uninstaller/id1013897218?mt=12
And let you see if it safe.

**Comment by redefinio** [comment]
Thanks for your support, Ricardo. Just to let you know, I really enjoy SuperCrypta and I'm using the paid version of it 👍

**Comment by ricardo85x** [comment]
nope it is a paid app I will find another

**Comment by ricardo85x** [comment]
Could i access your mac with teamviewer?
send me a email to supercrypta@gmail.com

**Comment by ricardo85x** [comment]
I was able to reproduce.

FIX:

remove SuperCrypta from the notification.
Wait 2 minutes(you have to wait because it will keep running for some seconds. You can check using Active Monitor and search for crypta)

Open Finder and type:

Command + SHIFT + G
type: ~/Library

Delete this:

Application Scripts/com.ricardoft.Cryptonator.SuperCrypta
Application Scripts/com.ricardoft.SuperCryptaHelper
Containers/com.ricardoft.Cryptonator.SuperCrypta
Containers/com.ricardoft.SuperCryptaHelper
Group Containers/B3YXS69JAV.group.com.ricardoft.supercrypta

Empty the Trash.

Now you can't add any coin.
To fix this you have to restart your Mac.

Could you try that?

**Comment by redefinio** [comment]
It worked! Thank you :) HODL!
